export const data = [
    {
        "BranchID": "vUcRWzgXtZFQt1qBApXFPQ==",
        "BranchId": "vUcRWzgXtZFQt1qBApXFPQ==",
        "ClientId": "RMkSD1QOzV9kXyuHKJCJrQ==",
        "Branch": "Trinidad",
        "Name": "c1@gmail.com",
        "CompanyWIthBranch": "c1@gmail.com (Trinidad)",
        "CompanyWithBranch": "c1@gmail.com (Trinidad)"
    },
    {
        "BranchID": "3STcQ5V60K2Myh5moapdeQ==",
        "BranchId": "3STcQ5V60K2Myh5moapdeQ==",
        "ClientId": "nBt8dsbTlnDRGeILKsxX0g==",
        "Branch": "Your Location Name",
        "Name": "c4@gmail.com",
        "CompanyWIthBranch": "c4@gmail.com (Your Location Name)",
        "CompanyWithBranch": "c4@gmail.com (Your Location Name)"
    },
    {
        "BranchID": "gb90vmUY0SR0d2A+IsRwXA==",
        "BranchId": "gb90vmUY0SR0d2A+IsRwXA==",
        "ClientId": "rkigMX27TkQxEMQ6wnTjYA==",
        "Branch": "Location 1",
        "Name": "c2@gmail.com",
        "CompanyWIthBranch": "c2@gmail.com (Location 1)",
        "CompanyWithBranch": "c2@gmail.com (Location 1)",
    }
]

export const list = [
  {
      "VisitID": "lm8Yq+9bTvQxRcj8VsSSiw==",
      "FirstName": "UserFirstName",
      "LastName": "UserLastName",
      "Gender": "",
      "GmailId": "vizitrtesting@gmail.com",
      "MobileNumber": "9009009001",
      "Phone": "9009009001",
      "BranchID": "vUcRWzgXtZFQt1qBApXFPQ==",
      "Company": "c1@gmail.com",
      "VehicleNo": "",
      "PurposeID": "A3exPiiOdxOd22fueheygg==",
      "Purpose": "",
      "Date": "21-Aug-2024",
      "ExpectedCheckIn": "21-Aug-2024 06:33 PM (IST)",
      "ExpectedCheckOut": "21-Aug-2024 07:35 PM (IST)",
      "CheckInDateTime": "",
      "CheckOutDateTime": "",
      "VizitrUserID": "SBwTeb+duGsyap8eCIGDgg==",
      "ClientId": "RMkSD1QOzV9kXyuHKJCJrQ==",
      "UserID": "FB17fLOqo3GfFKUg3fP/9g==",
      "Branch": "Trinidad",
      "TimeZone": "IST",
      "FullName": "UserFirstName UserLastName",
      "ExpectedCheckInDate": "2024-08-21T00:00:00",
      "ExpectedCheckInTime": "18:33",
      "ExpectedCheckOutDate": "2024-08-21T00:00:00",
      "ExpectedCheckOutTime": "19:35"
  },
  {
      "VisitID": "LmJPoKiVtu1cOiKoB/M2wg==",
      "FirstName": "UserFirstName",
      "LastName": "UserLastName",
      "Gender": "",
      "GmailId": "vizitrtesting@gmail.com",
      "EmailId": "vizitrtesting@gmail.com",
      "MobileNumber": "9009009001",
      "Phone": "9009009001",
      "BranchID": "vUcRWzgXtZFQt1qBApXFPQ==",
      "Company": "c1@gmail.com",
      "VehicleNo": "",
      "PurposeID": "A3exPiiOdxOd22fueheygg==",
      "Purpose": "",
      "Date": "07-Aug-2024",
      "ExpectedCheckIn": "07-Aug-2024 09:43 PM (IST)",
      "ExpectedCheckOut": "07-Aug-2024 10:43 PM (IST)",
      "CheckInDateTime": "",
      "CheckOutDateTime": "",
      "VizitrUserID": "SBwTeb+duGsyap8eCIGDgg==",
      "ClientId": "RMkSD1QOzV9kXyuHKJCJrQ==",
      "UserID": "FB17fLOqo3GfFKUg3fP/9g==",
      "Branch": "Trinidad",
      "TimeZone": "IST",
      "FullName": "UserFirstName UserLastName",
      "ExpectedCheckInDate": "2024-08-07T00:00:00",
      "ExpectedCheckInTime": "21:43",
      "ExpectedCheckOutDate": "2024-08-07T00:00:00",
      "ExpectedCheckOutTime": "22:43"
  },
  {
      "VisitID": "x2JbdrhfV+PuBfmDEl07QA==",
      "FirstName": "UserFirstName",
      "LastName": "UserLastName",
      "Gender": "",
      "GmailId": "vizitrtesting@gmail.com",
      "MobileNumber": "9009009001",
      "Phone": "9009009001",
      "BranchID": "vUcRWzgXtZFQt1qBApXFPQ==",
      "Company": "c1@gmail.com",
      "VehicleNo": "",
      "PurposeID": "A3exPiiOdxOd22fueheygg==",
      "Purpose": "",
      "Date": "07-Aug-2024",
      "ExpectedCheckIn": "07-Aug-2024 09:43 PM (IST)",
      "ExpectedCheckOut": "07-Aug-2024 10:43 PM (IST)",
      "CheckInDateTime": "",
      "CheckOutDateTime": "",
      "VizitrUserID": "SBwTeb+duGsyap8eCIGDgg==",
      "ClientId": "RMkSD1QOzV9kXyuHKJCJrQ==",
      "UserID": "FB17fLOqo3GfFKUg3fP/9g==",
      "Branch": "Trinidad",
      "TimeZone": "IST",
      "FullName": "UserFirstName UserLastName",
      "ExpectedCheckInDate": "2024-08-07T00:00:00",
      "ExpectedCheckInTime": "21:43",
      "ExpectedCheckOutDate": "2024-08-07T00:00:00",
      "ExpectedCheckOutTime": "22:43"
  },
  {
      "VisitID": "uelMtt/DTvzCVloHTAn7nQ==",
      "FirstName": "UserFirstName",
      "LastName": "UserLastName",
      "Gender": "",
      "GmailId": "vizitrtesting@gmail.com",
      "MobileNumber": "9009009001",
      "Phone": "9009009001",
      "BranchID": "vUcRWzgXtZFQt1qBApXFPQ==",
      "Company": "c1@gmail.com",
      "VehicleNo": "",
      "PurposeID": "A3exPiiOdxOd22fueheygg==",
      "Purpose": "",
      "Date": "07-Aug-2024",
      "ExpectedCheckIn": "07-Aug-2024 09:43 PM (IST)",
      "ExpectedCheckOut": "07-Aug-2024 10:43 PM (IST)",
      "CheckInDateTime": "",
      "CheckOutDateTime": "",
      "VizitrUserID": "SBwTeb+duGsyap8eCIGDgg==",
      "ClientId": "RMkSD1QOzV9kXyuHKJCJrQ==",
      "UserID": "FB17fLOqo3GfFKUg3fP/9g==",
      "Branch": "Trinidad",
      "TimeZone": "IST",
      "FullName": "UserFirstName UserLastName",
      "ExpectedCheckInDate": "2024-08-07T00:00:00",
      "ExpectedCheckInTime": "21:43",
      "ExpectedCheckOutDate": "2024-08-07T00:00:00",
      "ExpectedCheckOutTime": "22:43"
  }
]


export const windowList = [
    {
        Key: 15,
        value: 15
    },
    {
        Key: 30,
        value: 30
    },
    {
        Key: 60,
        value: 60
    },
    {
        Key: 120,
        value: 120
    },
]